# Generated by Django 3.0.7 on 2020-07-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=256)),
                ('autor', models.CharField(max_length=64)),
                ('an', models.IntegerField()),
                ('tara', models.CharField(max_length=64)),
                ('subiect', models.CharField(max_length=256)),
            ],
        ),
    ]
