# Generated by Django 2.2.5 on 2020-07-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200718_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='country',
        ),
        migrations.AddField(
            model_name='book',
            name='country',
            field=models.ManyToManyField(to='dashboard.Country'),
        ),
    ]
