# Generated by Django 2.2.5 on 2020-07-18 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200718_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='title',
            new_name='name',
        ),
    ]
