# Generated by Django 3.0.5 on 2020-07-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200718_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
