# Generated by Django 3.0.8 on 2020-07-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200726_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='country',
            field=models.ManyToManyField(to='dashboard.Country', verbose_name='Țări'),
        ),
        migrations.AlterField(
            model_name='book',
            name='languages',
            field=models.ManyToManyField(to='dashboard.Language', verbose_name='Limbi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='topics',
            field=models.ManyToManyField(to='dashboard.Topic', verbose_name='Categorii'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
