# Generated by Django 2.2 on 2020-07-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200726_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tracking',
            field=models.BooleanField(default=True),
        ),
    ]
