# Generated by Django 2.2 on 2020-07-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_book_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField()),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(max_length=64, unique=True)),
                ('datetime', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='tracking',
            field=models.BooleanField(default=False),
        ),
    ]
