# Generated by Django 3.0.3 on 2020-08-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200730_2244'),
        ('dashboard', '0011_book_status'),
    ]

    operations = [
    ]
