# Generated by Django 3.0.3 on 2020-08-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_merge_20200811_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.AlterField(
            model_name='book',
            name='tracking',
            field=models.BooleanField(default=False, null=True, verbose_name='Status carte'),
        ),
    ]
